//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OOPdbEntities : DbContext
    {
        public OOPdbEntities()
            : base("name=OOPdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attack> Attacks { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameShipConfiguration> GameShipConfigurations { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
